/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package allezon;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserTag extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4209243504345186908L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserTag\",\"namespace\":\"allezon\",\"fields\":[{\"name\":\"time\",\"type\":\"string\"},{\"name\":\"cookie\",\"type\":\"string\"},{\"name\":\"country\",\"type\":\"string\"},{\"name\":\"device\",\"type\":\"string\"},{\"name\":\"action\",\"type\":\"string\"},{\"name\":\"origin\",\"type\":\"string\"},{\"name\":\"product_info\",\"type\":{\"type\":\"record\",\"name\":\"ProductInfo\",\"fields\":[{\"name\":\"product_id\",\"type\":\"string\"},{\"name\":\"brand_id\",\"type\":\"string\"},{\"name\":\"category_id\",\"type\":\"string\"},{\"name\":\"price\",\"type\":\"int\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserTag> ENCODER =
      new BinaryMessageEncoder<UserTag>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserTag> DECODER =
      new BinaryMessageDecoder<UserTag>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserTag> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserTag> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserTag> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserTag>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserTag to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserTag from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserTag instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserTag fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence time;
  @Deprecated public java.lang.CharSequence cookie;
  @Deprecated public java.lang.CharSequence country;
  @Deprecated public java.lang.CharSequence device;
  @Deprecated public java.lang.CharSequence action;
  @Deprecated public java.lang.CharSequence origin;
  @Deprecated public allezon.ProductInfo product_info;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserTag() {}

  /**
   * All-args constructor.
   * @param time The new value for time
   * @param cookie The new value for cookie
   * @param country The new value for country
   * @param device The new value for device
   * @param action The new value for action
   * @param origin The new value for origin
   * @param product_info The new value for product_info
   */
  public UserTag(java.lang.CharSequence time, java.lang.CharSequence cookie, java.lang.CharSequence country, java.lang.CharSequence device, java.lang.CharSequence action, java.lang.CharSequence origin, allezon.ProductInfo product_info) {
    this.time = time;
    this.cookie = cookie;
    this.country = country;
    this.device = device;
    this.action = action;
    this.origin = origin;
    this.product_info = product_info;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return time;
    case 1: return cookie;
    case 2: return country;
    case 3: return device;
    case 4: return action;
    case 5: return origin;
    case 6: return product_info;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: time = (java.lang.CharSequence)value$; break;
    case 1: cookie = (java.lang.CharSequence)value$; break;
    case 2: country = (java.lang.CharSequence)value$; break;
    case 3: device = (java.lang.CharSequence)value$; break;
    case 4: action = (java.lang.CharSequence)value$; break;
    case 5: origin = (java.lang.CharSequence)value$; break;
    case 6: product_info = (allezon.ProductInfo)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'time' field.
   * @return The value of the 'time' field.
   */
  public java.lang.CharSequence getTime() {
    return time;
  }


  /**
   * Sets the value of the 'time' field.
   * @param value the value to set.
   */
  public void setTime(java.lang.CharSequence value) {
    this.time = value;
  }

  /**
   * Gets the value of the 'cookie' field.
   * @return The value of the 'cookie' field.
   */
  public java.lang.CharSequence getCookie() {
    return cookie;
  }


  /**
   * Sets the value of the 'cookie' field.
   * @param value the value to set.
   */
  public void setCookie(java.lang.CharSequence value) {
    this.cookie = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'device' field.
   * @return The value of the 'device' field.
   */
  public java.lang.CharSequence getDevice() {
    return device;
  }


  /**
   * Sets the value of the 'device' field.
   * @param value the value to set.
   */
  public void setDevice(java.lang.CharSequence value) {
    this.device = value;
  }

  /**
   * Gets the value of the 'action' field.
   * @return The value of the 'action' field.
   */
  public java.lang.CharSequence getAction() {
    return action;
  }


  /**
   * Sets the value of the 'action' field.
   * @param value the value to set.
   */
  public void setAction(java.lang.CharSequence value) {
    this.action = value;
  }

  /**
   * Gets the value of the 'origin' field.
   * @return The value of the 'origin' field.
   */
  public java.lang.CharSequence getOrigin() {
    return origin;
  }


  /**
   * Sets the value of the 'origin' field.
   * @param value the value to set.
   */
  public void setOrigin(java.lang.CharSequence value) {
    this.origin = value;
  }

  /**
   * Gets the value of the 'product_info' field.
   * @return The value of the 'product_info' field.
   */
  public allezon.ProductInfo getProductInfo() {
    return product_info;
  }


  /**
   * Sets the value of the 'product_info' field.
   * @param value the value to set.
   */
  public void setProductInfo(allezon.ProductInfo value) {
    this.product_info = value;
  }

  /**
   * Creates a new UserTag RecordBuilder.
   * @return A new UserTag RecordBuilder
   */
  public static allezon.UserTag.Builder newBuilder() {
    return new allezon.UserTag.Builder();
  }

  /**
   * Creates a new UserTag RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserTag RecordBuilder
   */
  public static allezon.UserTag.Builder newBuilder(allezon.UserTag.Builder other) {
    if (other == null) {
      return new allezon.UserTag.Builder();
    } else {
      return new allezon.UserTag.Builder(other);
    }
  }

  /**
   * Creates a new UserTag RecordBuilder by copying an existing UserTag instance.
   * @param other The existing instance to copy.
   * @return A new UserTag RecordBuilder
   */
  public static allezon.UserTag.Builder newBuilder(allezon.UserTag other) {
    if (other == null) {
      return new allezon.UserTag.Builder();
    } else {
      return new allezon.UserTag.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserTag instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserTag>
    implements org.apache.avro.data.RecordBuilder<UserTag> {

    private java.lang.CharSequence time;
    private java.lang.CharSequence cookie;
    private java.lang.CharSequence country;
    private java.lang.CharSequence device;
    private java.lang.CharSequence action;
    private java.lang.CharSequence origin;
    private allezon.ProductInfo product_info;
    private allezon.ProductInfo.Builder product_infoBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(allezon.UserTag.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.cookie)) {
        this.cookie = data().deepCopy(fields()[1].schema(), other.cookie);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.country)) {
        this.country = data().deepCopy(fields()[2].schema(), other.country);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.device)) {
        this.device = data().deepCopy(fields()[3].schema(), other.device);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.action)) {
        this.action = data().deepCopy(fields()[4].schema(), other.action);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.origin)) {
        this.origin = data().deepCopy(fields()[5].schema(), other.origin);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.product_info)) {
        this.product_info = data().deepCopy(fields()[6].schema(), other.product_info);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (other.hasProductInfoBuilder()) {
        this.product_infoBuilder = allezon.ProductInfo.newBuilder(other.getProductInfoBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing UserTag instance
     * @param other The existing instance to copy.
     */
    private Builder(allezon.UserTag other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.time)) {
        this.time = data().deepCopy(fields()[0].schema(), other.time);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cookie)) {
        this.cookie = data().deepCopy(fields()[1].schema(), other.cookie);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.country)) {
        this.country = data().deepCopy(fields()[2].schema(), other.country);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.device)) {
        this.device = data().deepCopy(fields()[3].schema(), other.device);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.action)) {
        this.action = data().deepCopy(fields()[4].schema(), other.action);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.origin)) {
        this.origin = data().deepCopy(fields()[5].schema(), other.origin);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.product_info)) {
        this.product_info = data().deepCopy(fields()[6].schema(), other.product_info);
        fieldSetFlags()[6] = true;
      }
      this.product_infoBuilder = null;
    }

    /**
      * Gets the value of the 'time' field.
      * @return The value.
      */
    public java.lang.CharSequence getTime() {
      return time;
    }


    /**
      * Sets the value of the 'time' field.
      * @param value The value of 'time'.
      * @return This builder.
      */
    public allezon.UserTag.Builder setTime(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.time = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'time' field has been set.
      * @return True if the 'time' field has been set, false otherwise.
      */
    public boolean hasTime() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'time' field.
      * @return This builder.
      */
    public allezon.UserTag.Builder clearTime() {
      time = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'cookie' field.
      * @return The value.
      */
    public java.lang.CharSequence getCookie() {
      return cookie;
    }


    /**
      * Sets the value of the 'cookie' field.
      * @param value The value of 'cookie'.
      * @return This builder.
      */
    public allezon.UserTag.Builder setCookie(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.cookie = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'cookie' field has been set.
      * @return True if the 'cookie' field has been set, false otherwise.
      */
    public boolean hasCookie() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'cookie' field.
      * @return This builder.
      */
    public allezon.UserTag.Builder clearCookie() {
      cookie = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public allezon.UserTag.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.country = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public allezon.UserTag.Builder clearCountry() {
      country = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'device' field.
      * @return The value.
      */
    public java.lang.CharSequence getDevice() {
      return device;
    }


    /**
      * Sets the value of the 'device' field.
      * @param value The value of 'device'.
      * @return This builder.
      */
    public allezon.UserTag.Builder setDevice(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.device = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'device' field has been set.
      * @return True if the 'device' field has been set, false otherwise.
      */
    public boolean hasDevice() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'device' field.
      * @return This builder.
      */
    public allezon.UserTag.Builder clearDevice() {
      device = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'action' field.
      * @return The value.
      */
    public java.lang.CharSequence getAction() {
      return action;
    }


    /**
      * Sets the value of the 'action' field.
      * @param value The value of 'action'.
      * @return This builder.
      */
    public allezon.UserTag.Builder setAction(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.action = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'action' field has been set.
      * @return True if the 'action' field has been set, false otherwise.
      */
    public boolean hasAction() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'action' field.
      * @return This builder.
      */
    public allezon.UserTag.Builder clearAction() {
      action = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'origin' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrigin() {
      return origin;
    }


    /**
      * Sets the value of the 'origin' field.
      * @param value The value of 'origin'.
      * @return This builder.
      */
    public allezon.UserTag.Builder setOrigin(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.origin = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'origin' field has been set.
      * @return True if the 'origin' field has been set, false otherwise.
      */
    public boolean hasOrigin() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'origin' field.
      * @return This builder.
      */
    public allezon.UserTag.Builder clearOrigin() {
      origin = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'product_info' field.
      * @return The value.
      */
    public allezon.ProductInfo getProductInfo() {
      return product_info;
    }


    /**
      * Sets the value of the 'product_info' field.
      * @param value The value of 'product_info'.
      * @return This builder.
      */
    public allezon.UserTag.Builder setProductInfo(allezon.ProductInfo value) {
      validate(fields()[6], value);
      this.product_infoBuilder = null;
      this.product_info = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'product_info' field has been set.
      * @return True if the 'product_info' field has been set, false otherwise.
      */
    public boolean hasProductInfo() {
      return fieldSetFlags()[6];
    }

    /**
     * Gets the Builder instance for the 'product_info' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public allezon.ProductInfo.Builder getProductInfoBuilder() {
      if (product_infoBuilder == null) {
        if (hasProductInfo()) {
          setProductInfoBuilder(allezon.ProductInfo.newBuilder(product_info));
        } else {
          setProductInfoBuilder(allezon.ProductInfo.newBuilder());
        }
      }
      return product_infoBuilder;
    }

    /**
     * Sets the Builder instance for the 'product_info' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public allezon.UserTag.Builder setProductInfoBuilder(allezon.ProductInfo.Builder value) {
      clearProductInfo();
      product_infoBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'product_info' field has an active Builder instance
     * @return True if the 'product_info' field has an active Builder instance
     */
    public boolean hasProductInfoBuilder() {
      return product_infoBuilder != null;
    }

    /**
      * Clears the value of the 'product_info' field.
      * @return This builder.
      */
    public allezon.UserTag.Builder clearProductInfo() {
      product_info = null;
      product_infoBuilder = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserTag build() {
      try {
        UserTag record = new UserTag();
        record.time = fieldSetFlags()[0] ? this.time : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.cookie = fieldSetFlags()[1] ? this.cookie : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.country = fieldSetFlags()[2] ? this.country : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.device = fieldSetFlags()[3] ? this.device : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.action = fieldSetFlags()[4] ? this.action : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.origin = fieldSetFlags()[5] ? this.origin : (java.lang.CharSequence) defaultValue(fields()[5]);
        if (product_infoBuilder != null) {
          try {
            record.product_info = this.product_infoBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("product_info"));
            throw e;
          }
        } else {
          record.product_info = fieldSetFlags()[6] ? this.product_info : (allezon.ProductInfo) defaultValue(fields()[6]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserTag>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserTag>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserTag>
    READER$ = (org.apache.avro.io.DatumReader<UserTag>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.time);

    out.writeString(this.cookie);

    out.writeString(this.country);

    out.writeString(this.device);

    out.writeString(this.action);

    out.writeString(this.origin);

    this.product_info.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.time = in.readString(this.time instanceof Utf8 ? (Utf8)this.time : null);

      this.cookie = in.readString(this.cookie instanceof Utf8 ? (Utf8)this.cookie : null);

      this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);

      this.device = in.readString(this.device instanceof Utf8 ? (Utf8)this.device : null);

      this.action = in.readString(this.action instanceof Utf8 ? (Utf8)this.action : null);

      this.origin = in.readString(this.origin instanceof Utf8 ? (Utf8)this.origin : null);

      if (this.product_info == null) {
        this.product_info = new allezon.ProductInfo();
      }
      this.product_info.customDecode(in);

    } else {
      for (int i = 0; i < 7; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.time = in.readString(this.time instanceof Utf8 ? (Utf8)this.time : null);
          break;

        case 1:
          this.cookie = in.readString(this.cookie instanceof Utf8 ? (Utf8)this.cookie : null);
          break;

        case 2:
          this.country = in.readString(this.country instanceof Utf8 ? (Utf8)this.country : null);
          break;

        case 3:
          this.device = in.readString(this.device instanceof Utf8 ? (Utf8)this.device : null);
          break;

        case 4:
          this.action = in.readString(this.action instanceof Utf8 ? (Utf8)this.action : null);
          break;

        case 5:
          this.origin = in.readString(this.origin instanceof Utf8 ? (Utf8)this.origin : null);
          break;

        case 6:
          if (this.product_info == null) {
            this.product_info = new allezon.ProductInfo();
          }
          this.product_info.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










